version: '3.8'
services:
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.2.0
    container_name: xxl-job-admin
    environment:
      PARAMS: '--spring.datasource.url=jdbc:mysql://47.115.138.120:3306/xxl_job?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
        --spring.datasource.username=xxx
        --spring.datasource.password=xxx'
    volumes:
      - /mydata:/data/applogs
    ports:
      - 8099:8080
    restart: always
