server:
  port: 7556

spring:
  application:
    name: seata1
  cloud:
    nacos:
      username: nacos
      password: root
      discovery:
        server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/seata?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

seata:
  applicationId: ${spring.application.name}
  txServiceGroup: seata-tx-group
  service:
    vgroup-mapping:
      seata-tx-group: default
    grouplist:
      default: localhost:8091

feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000