server:
  port: 8080

xxl.job:
  admin:
    addresses: http://47.115.138.120:8099/xxl-job-admin #集群用多个用逗号分隔
  accessToken: #非空开启
  executor:
    appname: xxl-job-executor-mrl #用于执行器分组，另需在调度中心配置
    address: ${EXECUTOR_ADDRESS:} #默认用address向调度中心注册，为null时用ip:port
    ip:   #默认自动获取ip，docker可能获取到的是内网ip 所以还需要在admin中手动配置为公网ip
    port: 9999 #默认9999，netty端口
    logpath: /data/applogs/xxl-job/jobhandler
    logretentiondays: 30